### ISSUE TITLE
求算法指导

### ISSUE THREAD

**Issue by ValiantCat** [nonstriater/Learn-Algorithms#1]
本人目前在做iOS 开发   虽然没毕业 但是评的职称也是高级工程师 ，做过javaEE  ，数据结构接触较少。 想在今年毕业的时候去阿里面试  ，大公司一般对算法要求较高 ，想专门学习下。
特意来问下初级的学习路线是 是按照 你推荐的基本初级书籍开始学还是直接从 代码层面看起。  或者有没有好的学习路线推荐

**Comment by nonstriater** [comment]
如果是应付面试，刷题就行了，可以看我推荐的几本刷题书籍。

**Comment by ValiantCat** [comment]
就是算法基础一般的也适合刷题？

**Comment by nonstriater** [comment]
基本的数据结构还是要过一遍，然后就是大量刷题

**Comment by lxtGH** [comment]
基本的数据结构都差不多了，基本算法（分治和递归啥的）也会一点，但就是不知道如何学习动态规划怎么办？？

**Comment by nonstriater** [comment]
@lxtGH 我们可以一起学习，一起完善这个repo
