### ISSUE TITLE
git clone 异常

### ISSUE THREAD

**Issue by tdouguo** [nonstriater/Learn-Algorithms#16]
$ git clone https://github.com/nonstriater/Learn-Algorithms.git
Cloning into 'Learn-Algorithms'...
remote: Enumerating objects: 831, done.
remote: Total 831 (delta 0), reused 0 (delta 0), pack-reused 831
Receiving objects: 100% (831/831), 3.30 MiB | 337.00 KiB/s, done.
Resolving deltas: 100% (416/416), done.
error: unable to create file Binary Tree/1-二叉树 /btree.c: No such file or directory
fatal: cannot create directory at 'Binary Tree/1-二叉树 /btree': No such file or directory
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by nonstriater** [comment]
按照错误提示再试下吧
