### ISSUE TITLE
能否提供付费答疑？

### ISSUE THREAD

**Issue by qxkxzw** [nonstriater/Learn-Algorithms#18]
我是 https://wen-ma.com 的开发者，请问能否提供付费答疑？

读者学习过程中遇到困难，向您支付50元，获得您20分钟的一对一帮助。

您可将网站的 定向提问链接 放在README.md中，方便读者直接对您提问。

我也不知道这算不算是广告，如果打扰了请批评指正。

**Comment by nonstriater** [comment]
谢邀，目前没时间，谢谢
