### ISSUE TITLE
关于仓库的疑问

### ISSUE THREAD

**Issue by YuanyeMa** [nonstriater/Learn-Algorithms#7]
我想请问一下，刚才在看仓库的时候发现没有代码，所以请问一下后期是否会有代码上传？还是说只是记录算法笔记用的？ 谢谢。

**Comment by nonstriater** [comment]
计划上每个算法都会写清楚思路，应用，代码实现。题目会写些思路，有些也会写代码实现，不会每个都写代码，没那么多时间
